/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. \u203C\uFE0F DO NOT MODIFY THIS FILE \u203C\uFE0F
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/article/[id]': RouteRecordInfo<'/article/[id]', '/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/coming-soon': RouteRecordInfo<'/coming-soon', '/coming-soon', Record<never, never>, Record<never, never>>,
    '/feed': RouteRecordInfo<'/feed', '/feed', Record<never, never>, Record<never, never>>,
    '/judges/': RouteRecordInfo<'/judges/', '/judges', Record<never, never>, Record<never, never>>,
    '/judges/[id]': RouteRecordInfo<'/judges/[id]', '/judges/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/judges/[id]/cases/': RouteRecordInfo<'/judges/[id]/cases/', '/judges/:id/cases', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/judges/[id]/profile/': RouteRecordInfo<'/judges/[id]/profile/', '/judges/:id/profile', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/judges/[id]/reviews/': RouteRecordInfo<'/judges/[id]/reviews/', '/judges/:id/reviews', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/judges/review/': RouteRecordInfo<'/judges/review/', '/judges/review', Record<never, never>, Record<never, never>>,
    '/judges/review/[id]': RouteRecordInfo<'/judges/review/[id]', '/judges/review/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/paywall': RouteRecordInfo<'/paywall', '/paywall', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/[id]/': RouteRecordInfo<'/profile/[id]/', '/profile/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/review/': RouteRecordInfo<'/review/', '/review', Record<never, never>, Record<never, never>>,
    '/review/[id]': RouteRecordInfo<'/review/[id]', '/review/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/review/new': RouteRecordInfo<'/review/new', '/review/new', Record<never, never>, Record<never, never>>,
    '/secret-marketing': RouteRecordInfo<'/secret-marketing', '/secret-marketing', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
